FIRST_SIGN_UP_BUTTON_ID = "com.example.android.tumblrx2:id/btn_signup"
SIGN_UP_WITH_EMAIL_ID = "com.example.android.tumblrx2:id/btn_signup_email"
INPUT_EMAIL_ID = "com.example.android.tumblrx2:id/et_email"
INPUT_PASSWORD_ID = "com.example.android.tumblrx2:id/et_password"
INPUT_USER_NAME_ID = "com.example.android.tumblrx2:id/et_username"
INPUT_AGE_ID = "com.example.android.tumblrx2:id/et_age"
DONE_BUTTON_ID = "com.example.android.tumblrx2:id/btn_signup"
ERROR_WRONG_MESSAGE_ID = "com.example.android.tumblrx2:id/tv_err_msg"