FIRST_LOG_IN_BUTTON_ID = "com.example.android.tumblrx2:id/btn_login"
LOG_IN_WITH_EMAIL_ID = "com.example.android.tumblrx2:id/btn_login_email"
INPUT_EMAIL_ID = "com.example.android.tumblrx2:id/et_email"
ERROR_MESSAGE_FOR_EMAIL_ID = "com.example.android.tumblrx2:id/tv_err_msg"
INPUT_PASSWORD_ID = "com.example.android.tumblrx2:id/et_password"
LOG_IN_BUTTON_ID = "com.example.android.tumblrx2:id/btn_login"
ERROR_MESSAGE_FOR_PASSWORD_ID = "com.example.android.tumblrx2:id/tv_err_msg"
