# class SearchBar:
HOME_MESSAGE_ICON_ID = "com.tumblr:id/notification_button_wrapper"
# MESSAGE_BUTTON_XPATH = "//android.widget.LinearLayout[@content-desc=\"Messages\"]"
A_FRIEND_XPATH= "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/androidx.viewpager.widget.ViewPager/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout"
SEND_BUTTON_ID = "com.tumblr:id/send_button"

SAY_SOMETHING_ID = "com.tumblr:id/edit_text"
CAMERA_ID = "com.tumblr:id/photo_button"
PHOTO_FROM_GALLERY_XPATH = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/android.widget.FrameLayout[2]/android.view.View"
PHOTO_FROM_CAMERA_ID = "com.tumblr:id/gallery_grid_header_camera_background"
TAKE_PHOTO_BUTTON_ID = "com.tumblr:id/camera_progress_bar"
SEND_TAKED_PHOTO_BUTTON_ID = "com.tumblr:id/next_button" 
GIF_ID = "com.tumblr:id/gif_button"
RECENT_ACCESSE_ID = "Recent"
CHOOSE_GIF_RECENT_XPATH = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/androidx.recyclerview.widget.RecyclerView/android.widget.ImageView[2]"
TOP_ACCESSE_ID = "top"
CHOOSE_GIF_TOP_XPATH = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.viewpager.widget.ViewPager/android.widget.FrameLayout/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.widget.ImageView[2]"
NEW_MESSAGE_ID = "com.tumblr:id/action_button"
NEW_MESSAGE_IMAGE_ID = "com.tumblr:id/image"
NEW_MESSAGE_GIF_ID = "com.tumblr:id/big_preview_image"
SEARCH_FOR_NEW_FRIND_ID = "com.tumblr:id/searchable_action_bar"
MY_NEW_FRIEND_XPATH = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/android.widget.RelativeLayout[1]/android.widget.LinearLayout"
LAST_MESSAGE_ID = "com.tumblr:id/message"
BACK_BUTTON_ACCESSE_ID = "Navigate up"
MORE_OPTIONS_ACCESSE_ID = "More options"
DELETE_CONVE_XPATH = "/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView/android.widget.LinearLayout[1]/android.widget.LinearLayout"
DELETE_BUTTON_TO_CONFIRM_ID = "android:id/button1"